version: '3.1'

services:
  db:
    build: .
    container_name: nestjs-typeorm-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql@14/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nestjs-typeorm-db
